### ISSUE TITLE
Inline images don't show up

### ISSUE THREAD

**Issue by stared** [leriomaggio/deep-learning-keras-tensorflow#13]
In the current version inline images in Markdown parts of Jupyter Notebook do not work (on least in GitHub), vide:

![screenshot 2017-04-14 22 09 59](https://cloud.githubusercontent.com/assets/1001610/25054727/2ac35abc-215f-11e7-962b-a6ec4c60fd0f.png)

**Comment by superMDguy** [comment]
Should be fixed by my pr

**Comment by leriomaggio** [comment]
Merged! 👍 

Thank you!
