### ISSUE TITLE
theano configuration error

### ISSUE THREAD

**Issue by akYoung** [leriomaggio/deep-learning-keras-tensorflow#3]
I want to configure the "device" in theanorc to "cpu“ but it raised a value error. 
And I removed the theanorc file, then it works.

**Comment by leriomaggio** [comment]
Hi @akYoung.

According to Theano documentation, the `cpu
I think that the problem may be rela

**Comment by akYoung** [comment]
The system is Ubuntu 16.04 64bit system. 
The ` $HOME/.theanorc` is configured as following. 
`
[global]
floatX = float32
device = cpu  # switch to cpu if no GPU is available on your machine

`
And when I import keras 
It shows the following error,
`Using Theano backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/akyang/anaconda3/envs/deep-learning/lib/python3.5/site-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/home/akyang/anaconda3/envs/deep-learning/lib/python3.5/site-packages/keras/backend/__init__.py", line 58, in <module>
    from .theano_backend import *
  File "/home/akyang/anaconda3/envs/deep-learning/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 1, in <module>
    import theano
  File "/home/akyang/anaconda3/envs/deep-learning/lib/python3.5/site-packages/theano/__init__.py", line 42, in <module>
    from theano.configdefaults import config
  File "/home/akyang/anaconda3/envs/deep-learning/lib/python3.5/site-packages/theano/configdefaults.py", line 109, in <module>
    in_c_key=False)
  File "/home/akyang/anaconda3/envs/deep-learning/lib/python3.5/site-packages/theano/configparser.py", line 276, in AddConfigVar
    configparam.__get__(root, type(root), delete_key=True)
  File "/home/akyang/anaconda3/envs/deep-learning/lib/python3.5/site-packages/theano/configparser.py", line 324, in __get__
    self.__set__(cls, val_str)
  File "/home/akyang/anaconda3/envs/deep-learning/lib/python3.5/site-packages/theano/configparser.py", line 335, in __set__
    self.val = self.filter(val)
  File "/home/akyang/anaconda3/envs/deep-learning/lib/python3.5/site-packages/theano/configdefaults.py", line 95, in filter
    % (self.default, val, self.fullname)))
ValueError: Invalid value ("cpu") for configuration variable "cpu  # switch to cpu if no GPU is available on your machine". Valid options start with one of "device", "gpu", "opencl", "cuda"
`

**Comment by drscotthawley** [comment]
I get essentially the same error on my Mac, when I set "device = cpu"

**Comment by drscotthawley** [comment]
If one leaves it as "gpu", then a different error results:

AttributeError: ('This name is already taken', 'floatX').

If one comments out the line in .theanorc with floatX in it, then the same error about floatX being already taken still occurs.

**Comment by ibrahim-amer** [comment]
I have exactly the same error but no solution worked for me. Please advice

Invalid value ("cpu") for configuration variable "gpu". Valid options start with one of "device", "opencl", "cuda"

**Comment by Hazarapet** [comment]
same problem for me.Is there any idea?

**Comment by akYoung** [comment]
Try removing ~/.theanorc.

**Comment by Hazarapet** [comment]
@akYoung how to remove that file? It's configuration file.

**Comment by Andrjusha** [comment]
I solved my problem by installing the new backend.

**Comment by Primula** [comment]
I insalled the new backend but it does not work for me...
Same error:
"ValueError: Invalid value (“cpu”) for configuration variable “gpu”. Valid options start with one of “device”, “opencl”, “cuda”"
Can you help me, please?

**Comment by akYoung** [comment]
@Hazarapet  It's been a long time and I am a little fuzzy about it. I suppose I just ran 'rm -rf ~/.theanorc' and it just worked. Maybe you can back it up and try removing it.

**Comment by Hazarapet** [comment]
I've already solved it.You should change "gpu0" to "cuda0"

**Comment by akYoung** [comment]
@Hazarapet  ok.

**Comment by Primula** [comment]
@Hazarapet Error is chnged now 
"ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.6 or higher required)
NoneType: None
Traceback (most recent call last):
  File "Desktop\TheanoCode\firstTest.py", line 9, in <module>
    x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
NameError: name 'shared' is not defined"

It seems to depend on the Theano beckend that I modified!
It's so instable!!!

**Comment by Hazarapet** [comment]
I forgot to say that you have to install "gpuarray"
http://deeplearning.net/software/libgpuarray/installation.html

**Comment by Primula** [comment]
I changed python version and now theano works!
I have installed python 2.7 by Anaconda and then theano by conda with pygpu.
At this moment the test seems to go :-)
Thanks a lot!

**Comment by leriomaggio** [comment]
Ok I think I should probably improve the part in which I explain how to properly setup `theano`:

Since version `0.9` they finally introduced the `libgpuarray` which was previously only available in the _development_ version.

These are the two options I came up with to properly install and configure `theano` on (ubuntu) Linux with **GPU** support:

1) [If you're using Anaconda] `conda install theano pygpu` should be just fine!

Sometimes it is suggested to install `pygpu` using the `conda-forge` channel:

`conda install -c conda-forge pygpu`

2) [Works with both Anaconda Python or Official CPython]

* Install `libgpuarray` from source: [Step-by-step install libgpuarray user library](http://deeplearning.net/software/libgpuarray/installation.html#step-by-step-install-user-library)

* Afterwards, installing `pygpu` from source: (in the same folder)
`python setup.py build && python setup.py install`

* `pip install theano`.


After **Theano is installed**:

echo "[global]
device = cuda
floatX = float32

[lib]
cnmem = 1.0" > ~/.theanorc

HTH

**Comment by leriomaggio** [comment]
@Primula it works with Python 3 as well. This is just to point out that it is not a matter of Python version ;)

**Comment by Primula** [comment]
Are you italian? Your name suggests me that's true.
I think I'll try Anaconda3 asap, but when I installed Theano by Anaconda2 it worked immediatly.
 I have Win 10, and in some Microsoft developer forum I find this option.
Finally, I'm Italian so if my impression is real, we may interact more clearly.
